# Generated by Django 4.0.5 on 2022-07-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
                ('nationalID', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('citizenImage', models.ImageField(upload_to='')),
                ('joinDate', models.DateTimeField(auto_now=True)),
                ('accountStatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_citizen',
            },
        ),
        migrations.CreateModel(
            name='CrimeList',
            fields=[
                ('crimeID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('crimeName', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'tbl_crimelist',
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('nationalID', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('crimeID', models.CharField(max_length=100)),
                ('criminalStatus', models.CharField(max_length=100)),
                ('locationArrested', models.CharField(max_length=100)),
                ('arrestDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_criminal',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('nationalID', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
                ('employmentStatus', models.BooleanField(default=False)),
                ('employmentDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_police_officer',
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('citizenID', models.IntegerField(default=0)),
                ('crimeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.crimelist')),
            ],
            options={
                'db_table': 'tbl_crimereport',
            },
        ),
    ]
