# Generated by Django 4.0.5 on 2022-07-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
                ('nationalID', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_citizen',
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('crimeNature', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_crime',
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('nationalID', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('crimeID', models.CharField(max_length=100)),
                ('criminalStatus', models.CharField(max_length=100)),
                ('locationArrested', models.CharField(max_length=100)),
                ('arrestDate', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_criminal',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('nationalID', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'tbl_police_officer',
            },
        ),
    ]
