# Generated by Django 4.0.5 on 2022-07-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crime',
            table='tbl_crime_report',
        ),
    ]
