# Generated by Django 4.0.5 on 2022-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_crimeanonymous_crime_reportdate_alter_crime_crimeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('evidenceFiles', models.ImageField(upload_to='')),
                ('Form', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'tbl_evidence',
            },
        ),
        migrations.CreateModel(
            name='OB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenID', models.IntegerField()),
                ('crimeID', models.IntegerField()),
                ('obNo', models.CharField(max_length=30)),
                ('reportDate', models.DateTimeField()),
                ('actionTaken', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('officerID', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='reportDate',
            new_name='reportTime',
        ),
    ]
